<?php
$locations = [
    'Kalanki', 'New Road', 'Ring Road', 'Kantipath', 'Thamel', 'Balaju', 'Koteshwor', 'Maitighar', 'Tripureshwor',
    'Jawalakhel', 'Pulchowk', 'Kupondole', 'Lagankhel', 'Patan Durbar Square', 'Bhaktapur Durbar Square',
    'Boudhanath', 'Swyambhunath', 'Dillibazar', 'Chabahil', 'Baneshwor', 'Maitidevi', 'Teku', 'Satdobato',
    'Pepsicola', 'Gongabu', 'Gairidhara', 'Maharajgunj', 'Bansbari', 'Tokha', 'Budhanilkantha', 'Jorpati',
    'Sankhu', 'Pharping', 'Kirtipur', 'Naikap', 'Basundhara', 'Samakhushi', 'Baluwatar', 'Naxal', 'Sinamangal',
    'Pashupatinath', 'Jawalakhel Zoo', 'Imadol', 'Lokanthali', 'Dhapasi' , 'Balambu', 'Satungal', 'Thankot', 'Dahachowk',
    'Gurjudhara', 'Kalimati', 'Balkhnu', 'Putalisadhak', 'Sundhara', 'RNAC', 'Guwarko','Tinthana', 'Mid-Baneshwor',
    'Sahidgate', 'Dalkhu', 'Dallu', 'Naya Bazar', 'Macchegaun',
];

$edges = [
    ['from' => 'Kalanki', 'to' => 'Ring Road', 'weight' => 4],
    ['from' => 'Ring Road', 'to' => 'Koteshwor', 'weight' => 8],
    ['from' => 'Koteshwor', 'to' => 'New Road', 'weight' => 6],
    ['from' => 'New Road', 'to' => 'Kantipath', 'weight' => 1.5],
    ['from' => 'Kantipath', 'to' => 'Thamel', 'weight' => 1],
    ['from' => 'Thamel', 'to' => 'Balaju', 'weight' => 3],
    ['from' => 'Balaju', 'to' => 'Gongabu', 'weight' => 2.5],
    ['from' => 'Gongabu', 'to' => 'Maharajgunj', 'weight' => 3],
    ['from' => 'Maharajgunj', 'to' => 'Budhanilkantha', 'weight' => 5],
    ['from' => 'Budhanilkantha', 'to' => 'Tokha', 'weight' => 4],
    ['from' => 'Koteshwor', 'to' => 'Baneshwor', 'weight' => 3],
    ['from' => 'Baneshwor', 'to' => 'Maitighar', 'weight' => 2.5],
    ['from' => 'Maitighar', 'to' => 'Tripureshwor', 'weight' => 1.5],
    ['from' => 'Tripureshwor', 'to' => 'Jawalakhel', 'weight' => 3],
    ['from' => 'Jawalakhel', 'to' => 'Pulchowk', 'weight' => 1],
    ['from' => 'Pulchowk', 'to' => 'Kupondole', 'weight' => 1],
    ['from' => 'Kupondole', 'to' => 'Lagankhel', 'weight' => 1.5],
    ['from' => 'Lagankhel', 'to' => 'Patan Durbar Square', 'weight' => 1],
    ['from' => 'Koteshwor', 'to' => 'Pepsicola', 'weight' => 3],
    ['from' => 'Pepsicola', 'to' => 'Bhaktapur Durbar Square', 'weight' => 10],
    ['from' => 'Bhaktapur Durbar Square', 'to' => 'Sankhu', 'weight' => 8],
    ['from' => 'Sankhu', 'to' => 'Jorpati', 'weight' => 9],
    ['from' => 'Jorpati', 'to' => 'Boudhanath', 'weight' => 3],
    ['from' => 'Boudhanath', 'to' => 'Chabahil', 'weight' => 2],
    ['from' => 'Chabahil', 'to' => 'Pashupatinath', 'weight' => 1],
    ['from' => 'Pashupatinath', 'to' => 'Sinamangal', 'weight' => 1.5],
    ['from' => 'Sinamangal', 'to' => 'Baneshwor', 'weight' => 2.5],
    ['from' => 'Dillibazar', 'to' => 'Maitidevi', 'weight' => 1.5],
    ['from' => 'Maitidevi', 'to' => 'Naxal', 'weight' => 2],
    ['from' => 'Naxal', 'to' => 'Baluwatar', 'weight' => 2],
    ['from' => 'Baluwatar', 'to' => 'Basundhara', 'weight' => 3],
    ['from' => 'Basundhara', 'to' => 'Samakhushi', 'weight' => 2],
    ['from' => 'Samakhushi', 'to' => 'Balaju', 'weight' => 3],
    ['from' => 'Balaju', 'to' => 'Swyambhunath', 'weight' => 4],
    ['from' => 'Swyambhunath', 'to' => 'Teku', 'weight' => 3],
    ['from' => 'Teku', 'to' => 'Tripureshwor', 'weight' => 2],
    ['from' => 'Kalanki', 'to' => 'Naikap', 'weight' => 5],
    ['from' => 'Naikap', 'to' => 'Kirtipur', 'weight' => 4],
    ['from' => 'Kirtipur', 'to' => 'Pharping', 'weight' => 10],
    // Add more edges as needed
];
?>
